#
# Module manifest for module 'PSImmich'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2024-03-07
#

@{
    RootModule           = 'PSImmich.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = '4c1238d7-f5de-400e-8543-3ea095a0ff34'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'Powershell wrapper for the Immich API'
    NestedModules        = @()
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            LicenseUri   = 'https://github.com/hanpq/PSImmich/blob/main/LICENSE'
            #RequireLicenseAcceptance = $false
            Prerelease   = ''
            Tags         = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            ProjectUri   = 'https://getps.dev/modules/PSImmich/getstarted'
            ReleaseNotes = ''
        }
    }
}
